name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    # Используем готовый образ, где всё уже настроено для Kivy
    container:
      image: ghcr.io/kivy/buildozer:master

    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        run: |
          # В этом образе всё уже установлено, просто запускаем
          buildozer -v android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 0

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TwinProject-APK
          path: bin/*.apk
          
